# Generated by Django 5.2.6 on 2025-09-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('kromik_no', models.CharField(max_length=50, verbose_name='ক্রমিক নং')),
                ('naam', models.TextField(verbose_name='নাম')),
                ('voter_no', models.CharField(max_length=100, verbose_name='ভোটার নং')),
                ('pitar_naam', models.TextField(verbose_name='পিতার নাম')),
                ('matar_naam', models.TextField(verbose_name='মাতার নাম')),
                ('pesha', models.TextField(verbose_name='পেশা')),
                ('occupation_details', models.TextField(blank=True, null=True)),
                ('jonmo_tarikh', models.CharField(max_length=100, verbose_name='জন্ম তারিখ')),
                ('thikana', models.TextField(verbose_name='ঠিকানা')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('tiktok_link', models.TextField(blank=True, null=True)),
                ('youtube_link', models.TextField(blank=True, null=True)),
                ('insta_link', models.TextField(blank=True, null=True)),
                ('photo_link', models.TextField(default='https://placehold.co/100x100/EEE/31343C?text=No+Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('political_status', models.TextField(blank=True, null=True)),
                ('relationship_status', models.CharField(default='Regular', max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.batch')),
            ],
        ),
    ]
