# Generated by Django 5.2.6 on 2025-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='jonmo_tarikh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='জন্ম তারিখ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='matar_naam',
            field=models.TextField(blank=True, null=True, verbose_name='মাতার নাম'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pesha',
            field=models.TextField(blank=True, null=True, verbose_name='পেশা'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pitar_naam',
            field=models.TextField(blank=True, null=True, verbose_name='পিতার নাম'),
        ),
        migrations.AlterField(
            model_name='record',
            name='thikana',
            field=models.TextField(blank=True, null=True, verbose_name='ঠিকানা'),
        ),
    ]
