# Generated by Django 5.2.6 on 2025-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_jonmo_tarikh_alter_record_matar_naam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='relationship_status',
            field=models.CharField(db_index=True, default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='voter_no',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ভোটার নং'),
        ),
    ]
