# Generated by Django 5.2.6 on 2025-09-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='records.record')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_of', to='records.record')),
            ],
            options={
                'unique_together': {('person', 'relative')},
            },
        ),
    ]
