# Generated by Django 5.2.6 on 2025-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_callhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='records', to='records.event'),
        ),
    ]
