# Generated by Django 5.2.6 on 2025-09-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_event_record_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.batch'),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='voter_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ভোটার নং'),
        ),
    ]
