# Generated by Django 5.2.6 on 2025-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_record_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
