# Stage 1: Prepare static files
FROM alpine:latest as builder
WORKDIR /app
COPY frontend/ .

# Stage 2: Serve the files with NGINX
FROM nginx:stable-alpine
COPY --from=builder /app /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
